version: '3.7'
services:

  tests:
    image: starlette_context
    container_name: starlette_context
    build: .
    command: ['pytest', '.']
    ports:
      - 8000:8000
    expose:
      - 8000
    restart: always
    volumes:
      - .:/source/starlette_context
